openapi: 3.0.3
info:
  title: StudyLog
  description: StudyLog
  version: 0.1.0
servers:
  - url: "https://localhost:8080"
paths:
  /api/v1/auth/mail/send:
    $ref: "./paths/v1/auth/send-mail.yaml"
  /api/v1/auth/mail/register:
    $ref: "./paths/v1/auth/register.yaml"
  /api/v1/auth/mail/login:
    $ref: "./paths/v1/auth/login.yaml"
  /api/v1/posts:
    $ref: "./paths/v1/post/posts.yaml"
  /api/v1/posts/{id}:
    $ref: "./paths/v1/post/post.yaml"
  /api/v1/studies:
    $ref: "./paths/v1/study/studies.yaml"

