openapi: 3.0.3
info:
  title: StudyLog
  description: StudyLog
  version: 0.1.0
servers:
  - url: "https://localhost:8080"
paths:
  # auth
  /api/v1/auth/email/send:
    $ref: "./paths/v1/auth/send-email.yaml"
  /api/v1/auth/email/signup:
    $ref: "./paths/v1/auth/signup.yaml"
  /api/v1/auth/email/signin:
    $ref: "./paths/v1/auth/signin.yaml"
  # post
  /api/v1/posts:
    $ref: "./paths/v1/post/posts.yaml"
  /api/v1/posts/{id}:
    $ref: "./paths/v1/post/post.yaml"
  /api/v1/posts/{id}/like:
    $ref: "./paths/v1/post/like.yaml"
  /api/v1/posts/{id}/unlike:
    $ref: "./paths/v1/post/unlike.yaml"
  /api/v1/{uid}/liked:
    $ref: "./paths/v1/post/liked.yaml"
  /api/v1/studies/{study-id}/posts/{post-id}:
    $ref: "./paths/v1/study/post.yaml"
  /api/v1/studies/{study-id}/posts/{post-id}/edit-request:
    $ref: "./paths/v1/study/edit-request.yaml"
  /api/v1/studies/{study-id}/posts/{post-id}/delete-request:
    $ref: "./paths/v1/study/delete-request.yaml"
  # search
  /api/v1/search/post:
    $ref: "./paths/v1/search/post.yaml"
  /api/v1/search/study:
    $ref: "./paths/v1/search/study.yaml"
  /api/v1/search/member:
    $ref: "./paths/v1/search/member.yaml"
  # member
  /api/v1/members:
    $ref: "./paths/v1/member/member.yaml"
  /api/v1/members/avatar-image:
    $ref: "./paths/v1/member/avatar-image.yaml"
  /api/v1/members/invites:
    $ref: "./paths/v1/member/invites.yaml"
  # study
  /api/v1/studies:
    $ref: "./paths/v1/study/studies.yaml"
  /api/v1/studies/{id}:
    $ref: "./paths/v1/study/study.yaml"
  /api/v1/studies/{id}/members:
    $ref: "./paths/v1/study/members.yaml"
  /api/v1/studies/{id}/posts:
    $ref: "./paths/v1/study/posts.yaml"
  /api/v1/{uid}/studies:
    $ref: "./paths/v1/study/my.yaml"
  /api/v1/studies/{id}/invite:
    $ref: "./paths/v1/study/invite.yaml"
  /api/v1/studies/{id}/join:
    $ref: "./paths/v1/study/join.yaml"
  /api/v1/studies/{id}/reject:
    $ref: "./paths/v1/study/reject.yaml"
  /api/v1/studies/{id}/invite/cancel:
    $ref: "./paths/v1/study/invite-cancel.yaml"
  /api/v1/studies/{id}/expel:
    $ref: "./paths/v1/study/expel.yaml"
  /api/v1/studies/{id}/delegate:
    $ref: "./paths/v1/study/delegate.yaml"
  /api/v1/studies/{id}/state:
    $ref: "./paths/v1/study/state.yaml"
  /api/v1/studies/{id}/withdraw:
    $ref: "./paths/v1/study/withdraw.yaml"
  # copy
  /api/v1/{uid}/copies:
    $ref: "./paths/v1/copy/copies.yaml"
  /api/v1/copies/{id}:
    $ref: "./paths/v1/copy/copy.yaml"
  # comment
  /api/v1/posts/{id}/comments:
    $ref: "./paths/v1/comment/comments.yaml"
  # reply
  /api/v1/comments/{id}/replies:
    $ref: "./paths/v1/reply/replies.yaml"
  # notice
  /api/v1/notices:
    $ref: "./paths/v1/notice/notices.yaml"

